local c = require("core.colorscheme")

require("nvim-web-devicons").set_icon({
  zsh = {
    icon = "",
    color = c.program_colours.zsh,
    cterm_color = "65",
    name = "Zsh",
  },
  php = {
    icon = "",
    color = c.program_colours.php,
    cterm_color = "140",
    name = "Php",
  },
  astro = {
    icon = "",
    color = c.program_colours.astro,
    cterm_color = "140",
    name = "astro",
  },
})

--
local M = {}
--   פּ ﯟ   some other good icons
M.cmp = {
  Function      = "  ",
  Constructor   = "  ",
  Class         = "  ",
  Module        = "  ",
  Number        = "  ",
  Color         = "  ",
  Folder        = "  ",
  Constant      = "  ",
  cmp_tabnine   = " ﮧ ",
  luasnip       = "  ",
  path          = " λ ",
  Array         = "  ",
  buffer        = " Ω ",
  File          = "  ",
  Boolean       = "  ",
  EnumMember    = "  ",
  Enum          = "  ",
  Event         = "  ",
  Field         = "  ",
  Key           = "  ",
  Interface     = "  ",
  Keyword       = "  ",
  Method        = "  ",
  Namespace     = "  ",
  Null          = " ﳠ",
  Object        = "  ",
  Operator      = "  ",
  Package       = "  ",
  Reference     = "  ",
  Property      = "  ",
  Snippet       = "  ",
  String        = "  ",
  Text          = "  ",
  Struct        = "  ",
  TypeParameter = "  ",
  Unit          = "  ",
  Value         = "  ",
  Variable      = "  ",
}

M.lunarvim = {
  kind = {
  },
  git = {
    LineAdded = "",
    LineModified = "",
    LineRemoved = "",
    FileDeleted = "",
    FileIgnored = "◌",
    FileRenamed = "",
    FileStaged = "S",
    FileUnmerged = "",
    FileUnstaged = "",
    FileUntracked = "U",
    Diff = "",
    Repo = "",
    Octoface = "",
    Branch = "",
  },
  ui = {
    ArrowCircleDown = "",
    ArrowCircleLeft = "",
    ArrowCircleRight = "",
    ArrowCircleUp = "",
    BoldArrowDown = "",
    BoldArrowLeft = "",
    BoldArrowRight = "",
    BoldArrowUp = "",
    BoldClose = "",
    BoldDividerLeft = "",
    BoldDividerRight = "",
    BoldLineLeft = "▎",
    BookMark = "",
    BoxChecked = "",
    Bug = "",
    Stacks = "",
    Scopes = "",
    Watches = "",
    DebugConsole = "",
    Calendar = "",
    Check = "",
    ChevronRight = ">",
    ChevronShortDown = "",
    ChevronShortLeft = "",
    ChevronShortRight = "",
    ChevronShortUp = "",
    Circle = "",
    Close = "",
    CloudDownload = "",
    Code = "",
    Comment = "",
    Dashboard = "",
    DividerLeft = "",
    DividerRight = "",
    DoubleChevronRight = "»",
    Ellipsis = "",
    EmptyFolder = "",
    EmptyFolderOpen = "",
    File = "",
    FileSymlink = "",
    Files = "",
    FindFile = "",
    FindText = "",
    Fire = "",
    Folder = "",
    FolderOpen = "",
    FolderSymlink = "",
    Forward = "",
    Gear = "",
    History = "",
    Lightbulb = "",
    LineLeft = "▏",
    LineMiddle = "│",
    List = "",
    Lock = "",
    NewFile = "",
    Note = "",
    Package = "",
    Pencil = "",
    Plus = "",
    Project = "",
    Search = "",
    SignIn = "",
    SignOut = "",
    Tab = "",
    Table = "",
    Target = "󰀘",
    Telescope = "",
    Text = "",
    Tree = "",
    Triangle = "契",
    TriangleShortArrowDown = "",
    TriangleShortArrowLeft = "",
    TriangleShortArrowRight = "",
    TriangleShortArrowUp = "",
  },
  diagnostics = {
    BoldError = "",
    Error = "",
    BoldWarning = "",
    Warning = "",
    BoldInformation = "",
    Information = "",
    BoldQuestion = "",
    Question = "",
    BoldHint = "",
    Hint = "",
    Debug = "",
    Trace = "✎",
  },
  misc = {
    Robot = "ﮧ",
    Squirrel = "",
    Tag = "",
    Watch = "",
    Smiley = "",
    Package = "",
    CircuitBoard = "",
  }
}

return M
